### ISSUE TITLE
block_cache assertion failures when running in NBD mode

### ISSUE THREAD

**Issue by Nikratio** [archiecobbs/s3backer#180] opened 2022-04-30 11:15 UTC
Hi,

I've been experimenting with NBD mode, and I'm at times getting the following error:

```
nbdkit: ../block_cache.c:1514: block_cache_check_invariants: Assertion `allow_stopping || !priv->stopping' failed.
```

So far, I have seen this happen only on shutdown (when `nbd-client -d /dev/nbd0` is called), but not every time.

When this happens, the mounted token is not cleaned up correctly.

What do you think?

**Comment by Nikratio** [comment] 2022-04-30 15:49
Update: this still happens when running from newest `nbd` branch:

```
2022-04-30 16:47:08 INFO: unmount nikratio-backup: initiated
2022-04-30 16:47:08 INFO: unmount nikratio-backup: shutting down filesystem
nbdkit: ../block_cache.c:1517: block_cache_check_invariants: Assertion `allow_stopping || !priv->stopping' failed.
```

**Comment by archiecobbs** [comment] 2022-04-30 19:51
I don't see how this happens unless NBD is (still) trying to read/write when it calls shutdown. But according to the man page it's not supposed to do that.

Probably it's an s3backer bug but I don't immediately see it. Needs more debugging to show the sequence of events.

What does the debug output look like? This is an example from my console that shows an orderly shutdown:
```
nbdkit: s3backer.8: debug: client sent NBD_CMD_DISC, closing connection
nbdkit: s3backer.8: debug: exiting worker thread s3backer.8
nbdkit: s3backer.2: debug: exiting worker thread s3backer.2
nbdkit: s3backer.0: debug: exiting worker thread s3backer.0
nbdkit: s3backer.4: debug: exiting worker thread s3backer.4
nbdkit: s3backer.11: debug: exiting worker thread s3backer.11
nbdkit: s3backer.9: debug: exiting worker thread s3backer.9
nbdkit: s3backer.12: debug: exiting worker thread s3backer.12
nbdkit: s3backer.15: debug: exiting worker thread s3backer.15
nbdkit: s3backer.3: debug: exiting worker thread s3backer.3
nbdkit: s3backer.7: debug: exiting worker thread s3backer.7
nbdkit: s3backer.14: debug: exiting worker thread s3backer.14
nbdkit: s3backer.5: debug: exiting worker thread s3backer.5
nbdkit: s3backer.13: debug: exiting worker thread s3backer.13
nbdkit: s3backer.6: debug: exiting worker thread s3backer.6
nbdkit: s3backer.1: debug: exiting worker thread s3backer.1
nbdkit: s3backer.10: debug: exiting worker thread s3backer.10
nbdkit: s3backer[1]: debug: exitlast: finalize
nbdkit: s3backer[1]: debug: s3backer: finalize
nbdkit: s3backer[1]: debug: exitlast: close
nbdkit: s3backer[1]: debug: exitlast: exiting on last client connection
nbdkit: s3backer[1]: debug: s3backer: close
nbdkit: debug: exitlast: cleanup
nbdkit: debug: s3backer: cleanup
2022-04-29 17:11:15 INFO: unmount archie-test: initiated
2022-04-29 17:11:15 INFO: unmount archie-test: shutting down filesystem
2022-04-29 17:11:15 INFO: unmount archie-test: clearing mount token
2022-04-29 17:11:15 INFO: unmount archie-test: completed
nbdkit: debug: s3backer: unload plugin
nbdkit: debug: exitlast: unload filter
```

**Comment by Nikratio** [comment] 2022-05-01 16:08
Hmm. At least in my last 5 tries, I was not able to reproduce the problem when running with debug logging - but on the 6th attempt (without debug logging) it happened again. Could be chance, or could be a race condition that is prevented by the extra time taken for writing debug output?

I can (more or less reliably) reproduce this by running the `create_zpool.py` script from my most recent pull request.

**Comment by Nikratio** [comment] 2022-05-01 16:11
Nevermind - finally worked:

```
2022-05-01 17:09:27 INFO: unmount nikratio-backup: initiated
2022-05-01 17:09:27 INFO: unmount nikratio-backup: shutting down filesystem
2022-05-01 17:09:27 DEBUG: PUT http://nikratio-backup.s3.eu-west-2.amazonaws.com/sb/0001c082
2022-05-01 17:09:27 DEBUG: PUT http://nikratio-backup.s3.eu-west-2.amazonaws.com/sb/00034081
2022-05-01 17:09:27 DEBUG: PUT http://nikratio-backup.s3.eu-west-2.amazonaws.com/sb/00018082
2022-05-01 17:09:27 DEBUG: PUT http://nikratio-backup.s3.eu-west-2.amazonaws.com/sb/00030080
2022-05-01 17:09:27 DEBUG: PUT http://nikratio-backup.s3.eu-west-2.amazonaws.com/sb/00000000
2022-05-01 17:09:27 DEBUG: PUT http://nikratio-backup.s3.eu-west-2.amazonaws.com/sb/0018fff0
2022-05-01 17:09:27 DEBUG: write aborted: PUT http://nikratio-backup.s3.eu-west-2.amazonaws.com/sb/00008084
2022-05-01 17:09:27 DEBUG: rec'd 404 response: GET http://nikratio-backup.s3.eu-west-2.amazonaws.com/sb/0001c086
nbdkit: ../block_cache.c:1517: block_cache_check_invariants: Assertion `allow_stopping || !priv->stopping' failed.
```

Full output is attached.
[nbdkit_sb.log](https://github.com/archiecobbs/s3backer/files/8599273/nbdkit_sb.log)

**Comment by archiecobbs** [comment] 2022-05-03 18:32
Here's the problem:
```
2022-05-01 17:14:44 DEBUG: GET http://nikratio-backup.s3.eu-west-2.amazonaws.com/sb/00034084
...
2022-05-01 17:14:44 INFO: unmount nikratio-backup: initiated
2022-05-01 17:14:44 INFO: unmount nikratio-backup: shutting down filesystem
...
2022-05-01 17:14:44 DEBUG: success: GET http://nikratio-backup.s3.eu-west-2.amazonaws.com/sb/00034084
nbdkit: ../block_cache.c:1517: block_cache_check_invariants: Assertion `allow_stopping || !priv->stopping' failed.
```

The only way I can see this happening is if NBDKit is initiating a shutdown while a read operation is still in progress (the read operation can't be from a worker thread because they check invariants with `allow_stopping == 1`).

So the log messages like `nbdkit: s3backer.1: debug: exiting worker thread s3backer.1` must not really mean the thread is exited, they only mean that the thread is going to exit when it gets a chance.

Seems like a bug in nbdkit... ?

If this is relatively easy to replicate, try running it under gdb and getting a stacktrace (using gdb's `where` command) when the assertion occurs. This will tell us exactly who is reading when they shouldn't be.

Thanks.

**Comment by rwmjones** [comment] 2022-05-05 13:38
Catching a core dump and doing gdb `t a a bt` to get a complete overview of what each thread is doing would be interesting.

**Comment by Nikratio** [comment] 2022-05-07 20:57
For reference, I am running this more or less daily but so far the problem has not recurred.

**Comment by archiecobbs** [comment] 2022-05-09 14:06
Can you identify the commit corresponding to the most recent time this problem occurred? There have been a few bug fixes, most notably versions >= 0ca29201 and < eb82d7db were broken.

**Comment by Nikratio** [comment] 2022-05-09 16:32
I'm not sure from which commit I had built, I'm afraid.

However, having updated to commit ae86d485 I am now getting different crashes:

```
munmap_chunk(): invalid pointer
free(): invalid pointer
```

It's difficult for me to narrow down what's going on here (and in issue #184) because there seem to be multiple issues, each triggered under slightly different conditions that sometimes hide each other. A test suite would help immensely with this.

I think I'll tackle this differently and start out from the other end - adding some simple multi-object support to nbdkit's existing S3 plugin and confirm that ZFS works correctly on top of that. Once I have that running, I have a better point of reference for ascertaining the effects of the various s3backer features.

**Comment by archiecobbs** [comment] 2022-05-09 17:06
Forgot to mention .. in theory the `--test` flag should be compatible with NBD mode. So this is another thing to try.

**Comment by rwmjones** [comment] 2022-05-09 17:41
In this case the stack traces don't tell us much.  All the threads are uninteresting apart from thread 1 where the failure happens, and that's just saying that glibc found an inconsistency in malloc structures when freeing an allocation (in your plugin, I think).  But it was almost certainly caused by earlier memory corruption which valgrind would usually be able to identify.

We run nbdkit itself under valgrind regularly (`make check-valgrind`) so we can be fairly certain that nbdkit itself doesn't have obvious memory corruption or leaking issues.  So this is more likely to be caused by the plugin and/or library you're using.

**Comment by archiecobbs** [comment] 2022-05-10 14:18
FYI I pushed some cleanups yesterday that should make valgrind happier...

**Comment by archiecobbs** [comment] 2022-05-21 22:28
Just curious if this is still happening with the latest code (d1bce951).

**Comment by archiecobbs** [comment] 2022-09-13 17:39
Closing issue assuming it's fixed.

**Closed by archiecobbs** 2022-09-13 17:39 UTC
